#!/bin/bash

# Copy/paste this job script into a text file and submit with the command:
#    sbatch thefilename
# job standard output will go to the file slurm-%j.out (where %j is the job ID)

#SBATCH --time=12:00:00   # walltime limit (HH:MM:SS)
#SBATCH --nodes=1   # number of nodes
#SBATCH --ntasks-per-node=16   # 16 processor core(s) per node
#SBATCH --job-name="2431"
#SBATCH --mail-user=rfortune@iastate.edu   # email address
#SBATCH --mail-type=BEGIN
#SBATCH --mail-type=END
#SBATCH --mail-type=FAIL

module load rsem/1.3.0-py2-r3.5-6w56sc6

module load  python/3.8.0-k7w5uj4

module load  bowtie2/2.3.4.1-py2-jl5zqym

cd /ptmp/aweeger/BCB546X_FinalGroup

rsem-calculate-expression -p 16 --bowtie2 --paired-end RNAseqData_E-MTAB-2431/ERR466673_1.fastq RNAseqData_E-MTAB-2431/ERR466673_2.fastq HG973349-HG973421 individual/early_cleavage_1

rsem-calculate-expression -p 16 --bowtie2 --paired-end RNAseqData_E-MTAB-2431/ERR466672_1.fastq RNAseqData_E-MTAB-2431/ERR466672_2.fastq HG973349-HG973421 individual/early_cleavage_2

rsem-calculate-expression -p 16 --bowtie2 --paired-end RNAseqData_E-MTAB-2431/ERR466680_1.fastq RNAseqData_E-MTAB-2431/ERR466680_2.fastq HG973349-HG973421 individual/early_postinversion_1

rsem-calculate-expression -p 16 --bowtie2 --paired-end RNAseqData_E-MTAB-2431/ERR466668_1.fastq RNAseqData_E-MTAB-2431/ERR466668_2.fastq HG973349-HG973421 individual/early_postinversion_2

rsem-calculate-expression -p 16 --bowtie2 --paired-end RNAseqData_E-MTAB-2431/ERR466669_1.fastq RNAseqData_E-MTAB-2431/ERR466669_2.fastq HG973349-HG973421 individual/early_preinversion_1

rsem-calculate-expression -p 16 --bowtie2 --paired-end RNAseqData_E-MTAB-2431/ERR466675_1.fastq RNAseqData_E-MTAB-2431/ERR466675_2.fastq HG973349-HG973421 individual/early_preinversion_2

rsem-calculate-expression -p 16 --bowtie2 --paired-end RNAseqData_E-MTAB-2431/ERR466667_1.fastq RNAseqData_E-MTAB-2431/ERR466667_2.fastq HG973349-HG973421 individual/early_vitellogenesis_1

rsem-calculate-expression -p 16 --bowtie2 --paired-end RNAseqData_E-MTAB-2431/ERR466682_1.fastq RNAseqData_E-MTAB-2431/ERR466682_2.fastq HG973349-HG973421 individual/early_vitellogenesis_2

rsem-calculate-expression -p 16 --bowtie2 --paired-end RNAseqData_E-MTAB-2431/ERR466666_1.fastq RNAseqData_E-MTAB-2431/ERR466666_2.fastq HG973349-HG973421 individual/early_vitellogenesis_3

rsem-calculate-expression -p 16 --bowtie2 --paired-end RNAseqData_E-MTAB-2431/ERR466670_1.fastq RNAseqData_E-MTAB-2431/ERR466670_2.fastq HG973349-HG973421 individual/fertilization_2

rsem-calculate-expression -p 16 --bowtie2 --paired-end RNAseqData_E-MTAB-2431/ERR466664_1.fastq RNAseqData_E-MTAB-2431/ERR466664_2.fastq HG973349-HG973421 individual/fertilization_1
